export const images = {
  excavator: require('@assets/images/excavator.png'),
  heavyDutyForklift: require('@assets/images/heavy-duty-forklift.png'),
  roller: require('@assets/images/roller.png'),
  truckCrane: require('@assets/images/truck-crane.png'),
  truckMixer: require('@assets/images/truck-mixer.png'),
  wheelLoader: require('@assets/images/wheel-loader.png'),
  portMachinery: require('@assets/images/port-machinery.png'),
  powerSystems: require('@assets/images/power-system.png'),
  spareParts: require('@assets/images/spare-parts.png'),
  allTerrainCrane: require('@assets/images/all-terrain-crane.svg'),
  roughTerrainCrane: require('@assets/images/rough-terrain-crane.svg'),
  towerCrane: require('@assets/images/tower-crane.svg'),
  crawlerCrane: require('@assets/images/crawler-crane.svg'),
  forkliftTrucks: require('@assets/images/forklift-trucks.png'),
  warehouseEquipments: require('@assets/images/warehouse-equipments.png'),
  aerialPlatform: require('@assets/images/aerial-platform.svg'),
  truckMountedConcretePump: require('@assets/images/truck-mounted-concrete-pump.svg'),
  trailerPump: require('@assets/images/trailer-pump.svg'),
  placingBoom: require('@assets/images/placing-boom.png'),
  batchingPlant: require('@assets/images/batching-plant.svg'),
  motorGrader: require('@assets/images/motor-grader.svg'),
  reachStacker: require('@assets/images/reach-stacker.svg'),
  emptyContainerHandler: require('@assets/images/empty-container-handler.svg'),
  powerGenerator: require('@assets/images/power-generator.svg'),
  bussEngines: require('@assets/images/buss-engines.svg'),
} as const;
